#DMW MINI PROJECT
> Varun Gadde BECOB203 <br>
> Vedant Upganlawar BECOB270 
## BANK CUSTOMERS EXITNG PREDICTIVE MODEL
###A bank is investigating a very high rate of customer leaving the bank. Here is a 10,000 records dataset to investigate and predict which of the customers are more likely to leave the bank soon.

###IPYNB FLOW
* [i. Loading Libraries](#A) <br>
* [ii. Importing data](#B) <br>
* [1.Dropping unnecessary columns](#1) <br>
* [2.Variable Analysis](#2) <br>
    * [2.1. Categorical Variables](#2.1) <br>
    * [2.2. Numerical Variables](#2.1) <br>
* [3.Machine Learning](#3) <br>
    * [3.1. Modelling](#3.1) <br>
    * [3.2. Logistic Regression](#3.2) <br>
    * [3.3. Classification with KNN (K Neirest Neighbour)](#3.3) <br>
    * [3.4. Classification with SVM (Support Vector Machine)](#3.4) <br>
    * [3.5. Classification with Naive Bayes](#3.5) <br>
    * [3.6. Classification with Random Forest](#3.6) <br>
    * [3.7. K-Fold Cross Validation (cross_val_score)](#3.7) <br>

<a id="A"></a>
## i. Loading Libraries

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

<a id="B"></a>
## ii. Importing data

In [2]:
# Read data
!git clone https://github.com/varungadde99/DMW-Mini-Project-Classification-SPPU.git


Cloning into 'DMW-Mini-Project-Classification-SPPU'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.


In [3]:
%cd DMW-Mini-Project-Classification-SPPU
data = pd.read_csv("Churn_Modelling.csv")

/content/DMW-Mini-Project-Classification-SPPU


In [4]:
# First 10 rows of data
data.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [5]:
# Statistical infos on data
data.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [6]:

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


* From above, we understood that there is no missing value in columns.
* There are 10000 items and each columns has 10000 non-null items.
* We can check missing value also by isnull() method as below:

In [7]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

<a id="1"></a>
## 1. Dropping unnecessary columns

In [8]:
data.drop(["RowNumber","CustomerId","Surname"], axis=1, inplace=True)
data.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

<a id="2"></a>
# 2.VARIABLE ANALYSIS

### Categorical Variables:
* Geography
* Gender	
* HasCrCard	
* IsActiveMember	
* Exited
* NumOfProducts

### Numerical Variables: 
* CreditScore	
* Age	
* Tenure	
* Balance	
* EstimatedSalary

<a id="5"></a>
# 3. MACHINE LEARNING

In [9]:
#definign a function that normalizes selected feature of a selected data

def normalize_feature(variable, data1):
    data1[variable] = (data1[variable] - np.min(data1[variable]))/(np.max(data1[variable] - np.min(data1[variable])))

In [10]:
# Normalizing some features in a for loop:
#for each in ['CreditScore','Age', 'Tenure', 'Balance','EstimatedSalary']:
    #normalize_feature(each, new_data)

## Converting "Geography" and "Gender" to categoricals:
* Geography --> Geography_France  / Geography_Germany / Geography_Spain
* Gender --> Gender_Female  / Gender_Male


In [11]:
df = data.copy()

In [12]:
df["Geography"] = df.Geography.astype("category")
df["Gender"] = df.Gender.astype("category")
df = pd.get_dummies(df,columns=["Geography","Gender"])

In [13]:
df.head()

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0          619   42       2  ...                0              1            0
1          608   41       1  ...                1              1            0
2          502   42       8  ...                0              1            0
3          699   39       1  ...                0              1            0
4          850   43       2  ...                1              1            0

[5 rows x 14 columns]

## Converting "Tenure" and "NumOfProducts" to categorical

In [14]:
df["Tenure"] = df.Tenure.astype("category")
df["NumOfProducts"] = df.NumOfProducts.astype("category")
df = pd.get_dummies(df, columns=(["Tenure","NumOfProducts"]))

## Converting data types of columns to category

In [15]:
for each in ["HasCrCard","IsActiveMember","Exited"]:
    df[each] = df[each].astype("category")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   CreditScore        10000 non-null  int64   
 1   Age                10000 non-null  int64   
 2   Balance            10000 non-null  float64 
 3   HasCrCard          10000 non-null  category
 4   IsActiveMember     10000 non-null  category
 5   EstimatedSalary    10000 non-null  float64 
 6   Exited             10000 non-null  category
 7   Geography_France   10000 non-null  uint8   
 8   Geography_Germany  10000 non-null  uint8   
 9   Geography_Spain    10000 non-null  uint8   
 10  Gender_Female      10000 non-null  uint8   
 11  Gender_Male        10000 non-null  uint8   
 12  Tenure_0           10000 non-null  uint8   
 13  Tenure_1           10000 non-null  uint8   
 14  Tenure_2           10000 non-null  uint8   
 15  Tenure_3           10000 non-null  uint8   
 16  Tenur

In [17]:
df.head(8)

CreditScore  Age  ...  NumOfProducts_3 NumOfProducts_4
0          619   42  ...                0               0
1          608   41  ...                0               0
2          502   42  ...                1               0
3          699   39  ...                0               0
4          850   43  ...                0               0
5          645   44  ...                0               0
6          822   50  ...                0               0
7          376   29  ...                0               1

[8 rows x 27 columns]

<a id="5.1"></a>
## 3.1. Modelling

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


## Train - test split

### Creating X_train:

In [19]:
#creating X_train and y_train 
X_train = df.drop("Exited", axis = 1)
y_train = df["Exited"]

#Features (CreditScore, Age, Balance, EstimatedSalary) to be normalized:
for each in ["CreditScore", "Age", "Balance", "EstimatedSalary"]:
    normalize_feature(each, X_train)

#X_train and Y_train data shape summary
print("Length of X_train: ",len(X_train))
print("Shape of X_train: ", X_train.shape)
print("Length of Y_tain: ", len(y_train))
print("Shape of Y_train: ", y_train.shape)

Length of X_train:  10000
Shape of X_train:  (10000, 26)
Length of Y_tain:  10000
Shape of Y_train:  (10000,)


* Features (CreditScore, Age, Balance, EstimatedSalary) to be normalized:

In [20]:
X_train.describe()

CreditScore           Age  ...  NumOfProducts_3  NumOfProducts_4
count  10000.000000  10000.000000  ...     10000.000000     10000.000000
mean       0.601058      0.282727  ...         0.026600         0.006000
std        0.193307      0.141727  ...         0.160919         0.077231
min        0.000000      0.000000  ...         0.000000         0.000000
25%        0.468000      0.189189  ...         0.000000         0.000000
50%        0.604000      0.256757  ...         0.000000         0.000000
75%        0.736000      0.351351  ...         0.000000         0.000000
max        1.000000      1.000000  ...         1.000000         1.000000

[8 rows x 24 columns]

### Creating y_train:

### Splitting X_Train, y_train

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_train, 
    y_train, 
    test_size = 0.33, 
    random_state = 42
)

print("Length of X_train: ",len(X_train))
print("Length of X_test: ",len(X_test))
print("Length of y_train: ",len(y_train))
print("Length of y_test: ",len(y_test))

Length of X_train:  6700
Length of X_test:  3300
Length of y_train:  6700
Length of y_test:  3300


![image.png](attachment:image.png)

<a id="5.2"></a>
## 3.2. Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

lr = LogisticRegression(random_state = 1)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

print("Accuracy with test data: ",round(lr.score(X_test, y_test)*100))
cm=confusion_matrix(y_test,y_pred)
print()
print(cm)
print()
print(classification_report(y_test, y_pred))

Accuracy with test data:  85.0

[[2552  105]
 [ 399  244]]

              precision    recall  f1-score   support

           0       0.86      0.96      0.91      2657
           1       0.70      0.38      0.49       643

    accuracy                           0.85      3300
   macro avg       0.78      0.67      0.70      3300
weighted avg       0.83      0.85      0.83      3300



<a id="5.3"></a>
## 3.3. Classification with KNN (K Neirest Neighbour)

### Calculation for single n-neighbor

In [23]:
# Single run for 4-neighbors:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)

print("4-neighbors KNN accuracy with test data: ", round(knn.score(X_test,y_test)*100))
cm=confusion_matrix(y_test,y_pred)
print()
print(cm)
print()
print(classification_report(y_test, y_pred))


4-neighbors KNN accuracy with test data:  82.0

[[2559   98]
 [ 502  141]]

              precision    recall  f1-score   support

           0       0.84      0.96      0.90      2657
           1       0.59      0.22      0.32       643

    accuracy                           0.82      3300
   macro avg       0.71      0.59      0.61      3300
weighted avg       0.79      0.82      0.78      3300



<a id="5.4"></a>
## 3.4. Classification with SVM (Support Vector Machine)

In [24]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


svm = SVC(random_state = 1)
svm.fit(X_train, y_train)
y_pred=svm.predict(X_test)

print("SVM accuracy with test data :", svm.score(X_test, y_test)*100)
cm=confusion_matrix(y_test,y_pred)
print()
print(cm)
print()
print(classification_report(y_test, y_pred))

SVM accuracy with test data : 84.66666666666667

[[2602   55]
 [ 451  192]]

              precision    recall  f1-score   support

           0       0.85      0.98      0.91      2657
           1       0.78      0.30      0.43       643

    accuracy                           0.85      3300
   macro avg       0.81      0.64      0.67      3300
weighted avg       0.84      0.85      0.82      3300



<a id="5.5"></a>
## 3.5. Classification with Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred=nb.predict(X_test)

print("NB accuracy with test data :", nb.score(X_test, y_test)*100)
cm=confusion_matrix(y_test,y_pred)
print()
print(cm)
print()
print(classification_report(y_test, y_pred))

NB accuracy with test data : 82.78787878787878

[[2638   19]
 [ 549   94]]

              precision    recall  f1-score   support

           0       0.83      0.99      0.90      2657
           1       0.83      0.15      0.25       643

    accuracy                           0.83      3300
   macro avg       0.83      0.57      0.58      3300
weighted avg       0.83      0.83      0.78      3300



<a id="5.7"></a>
## 3.6. Classification with Random Forest

### RF classification with single n-estimator

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

rf = RandomForestClassifier(n_estimators = 24, random_state = 42)
rf.fit(X_train, y_train)
y_pred=rf.predict(X_test)

print("RF accuracy with test data :", rf.score(X_test, y_test)*100)
cm=confusion_matrix(y_test,y_pred)
print()
print(cm)
print()
print(classification_report(y_test, y_pred))

RF accuracy with test data : 86.51515151515152

[[2554  103]
 [ 342  301]]

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2657
           1       0.75      0.47      0.57       643

    accuracy                           0.87      3300
   macro avg       0.81      0.71      0.75      3300
weighted avg       0.86      0.87      0.85      3300



## <a id="5.8"></a>
## 3.7. K-Fold Cross Validation (cross_val_score)

#### accuracies = cross_val_score(estimator = knn, X = x_train, y=y_train, cv=10) 

* Algorithm:
1.     1- Split data as train and test datas.
1.     2- Let say k of k-fold is 3, then train data to be splitted into 3.
1.     3- Split each train data into 3 again as train-train-validation.
1.     4- For each 3 splits, data to be trained and validated.
1.     5- There will be 3 accuracy rate for each 3 trains.
1.     6- Get mean of 3 accuracies.
1.     7- Test the model with test split.

In [27]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator =knn, X = X_train, y = y_train, cv = 10)
print("accuracies :",accuracies)
print("mean accuracy of KNN:", accuracies.mean()*100)

accuracies : [0.79402985 0.79850746 0.81044776 0.80447761 0.79402985 0.8
 0.79253731 0.81492537 0.8        0.8119403 ]
mean accuracy of KNN: 80.2089552238806
